clc;
clear all;
close all;
CONSTRAINTLENGTH=3
CODEGENERATOR=[5,7]
TRELLIS = poly2trellis(CONSTRAINTLENGTH,CODEGENERATOR)
CODE = convenv(MSG,TRELLIS)
TBLEN=log2(TRELLIS.numOutputSymbols)
OPMODE='trunc'
DECTYPE= 'hard'
DECODED = vitdec(CODE,TRELLIS,TBLEN,OPMODE,DECTYPE)
